/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG) && ENABLE(SVG_FILTERS)

#include "Document.h"
#include "Frame.h"
#include "SVGDocumentExtensions.h"
#include "SVGElement.h"
#include "SVGAnimatedTemplate.h"
#include "JSSVGFEPointLightElement.h"

#include <wtf/GetPtr.h>

#include "JSSVGAnimatedNumber.h"
#include "SVGFEPointLightElement.h"


using namespace JSC;

namespace WebCore {

ASSERT_CLASS_FITS_IN_CELL(JSSVGFEPointLightElement)

/* Hash table */

static const HashTableValue JSSVGFEPointLightElementTableValues[4] =
{
    { "x", (intptr_t)JSSVGFEPointLightElement::XAttrNum, DontDelete|ReadOnly, 0 },
    { "y", (intptr_t)JSSVGFEPointLightElement::YAttrNum, DontDelete|ReadOnly, 0 },
    { "z", (intptr_t)JSSVGFEPointLightElement::ZAttrNum, DontDelete|ReadOnly, 0 },
    { 0, 0, 0, 0 }
};

static const HashTable JSSVGFEPointLightElementTable = { 3, JSSVGFEPointLightElementTableValues, 0 };

/* Hash table for prototype */

static const HashTableValue JSSVGFEPointLightElementPrototypeTableValues[1] =
{
    { 0, 0, 0, 0 }
};

static const HashTable JSSVGFEPointLightElementPrototypeTable = { 0, JSSVGFEPointLightElementPrototypeTableValues, 0 };

const ClassInfo JSSVGFEPointLightElementPrototype::s_info = { "SVGFEPointLightElementPrototype", 0, &JSSVGFEPointLightElementPrototypeTable, 0 };

JSObject* JSSVGFEPointLightElementPrototype::self(ExecState* exec)
{
    static const Identifier* prototypeIdentifier = new Identifier(exec, "[[JSSVGFEPointLightElement.prototype]]");
    return JSC::cacheGlobalObject<JSSVGFEPointLightElementPrototype>(exec, *prototypeIdentifier);
}

const ClassInfo JSSVGFEPointLightElement::s_info = { "SVGFEPointLightElement", &JSSVGElement::s_info, &JSSVGFEPointLightElementTable , 0 };

JSSVGFEPointLightElement::JSSVGFEPointLightElement(JSObject* prototype, SVGFEPointLightElement* impl)
    : JSSVGElement(prototype, impl)
{
}

bool JSSVGFEPointLightElement::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGFEPointLightElement, Base>(exec, &JSSVGFEPointLightElementTable, this, propertyName, slot);
}

JSValue* JSSVGFEPointLightElement::getValueProperty(ExecState* exec, int token) const
{
    switch (token) {
    case XAttrNum: {
        SVGFEPointLightElement* imp = static_cast<SVGFEPointLightElement*>(impl());
        RefPtr<SVGAnimatedNumber> obj = imp->xAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case YAttrNum: {
        SVGFEPointLightElement* imp = static_cast<SVGFEPointLightElement*>(impl());
        RefPtr<SVGAnimatedNumber> obj = imp->yAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ZAttrNum: {
        SVGFEPointLightElement* imp = static_cast<SVGFEPointLightElement*>(impl());
        RefPtr<SVGAnimatedNumber> obj = imp->zAnimated();
        return toJS(exec, obj.get(), imp);
    }
    }
    return 0;
}


}

#endif // ENABLE(SVG) && ENABLE(SVG_FILTERS)
