/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"


#if ENABLE(SVG) && ENABLE(SVG_FILTERS)

#include "Document.h"
#include "Frame.h"
#include "SVGDocumentExtensions.h"
#include "SVGElement.h"
#include "SVGAnimatedTemplate.h"
#include "JSSVGFETurbulenceElement.h"

#include <wtf/GetPtr.h>

#include "CSSMutableStyleDeclaration.h"
#include "CSSStyleDeclaration.h"
#include "CSSValue.h"
#include "JSCSSStyleDeclaration.h"
#include "JSCSSValue.h"
#include "JSSVGAnimatedEnumeration.h"
#include "JSSVGAnimatedInteger.h"
#include "JSSVGAnimatedLength.h"
#include "JSSVGAnimatedNumber.h"
#include "JSSVGAnimatedString.h"
#include "SVGFETurbulenceElement.h"

#include <kjs/Error.h>
#include <kjs/JSNumberCell.h>

using namespace JSC;

namespace WebCore {

ASSERT_CLASS_FITS_IN_CELL(JSSVGFETurbulenceElement)

/* Hash table */

static const HashTableValue JSSVGFETurbulenceElementTableValues[15] =
{
    { "baseFrequencyX", (intptr_t)JSSVGFETurbulenceElement::BaseFrequencyXAttrNum, DontDelete|ReadOnly, 0 },
    { "baseFrequencyY", (intptr_t)JSSVGFETurbulenceElement::BaseFrequencyYAttrNum, DontDelete|ReadOnly, 0 },
    { "numOctaves", (intptr_t)JSSVGFETurbulenceElement::NumOctavesAttrNum, DontDelete|ReadOnly, 0 },
    { "seed", (intptr_t)JSSVGFETurbulenceElement::SeedAttrNum, DontDelete|ReadOnly, 0 },
    { "stitchTiles", (intptr_t)JSSVGFETurbulenceElement::StitchTilesAttrNum, DontDelete|ReadOnly, 0 },
    { "type", (intptr_t)JSSVGFETurbulenceElement::TypeAttrNum, DontDelete|ReadOnly, 0 },
    { "x", (intptr_t)JSSVGFETurbulenceElement::XAttrNum, DontDelete|ReadOnly, 0 },
    { "y", (intptr_t)JSSVGFETurbulenceElement::YAttrNum, DontDelete|ReadOnly, 0 },
    { "width", (intptr_t)JSSVGFETurbulenceElement::WidthAttrNum, DontDelete|ReadOnly, 0 },
    { "height", (intptr_t)JSSVGFETurbulenceElement::HeightAttrNum, DontDelete|ReadOnly, 0 },
    { "result", (intptr_t)JSSVGFETurbulenceElement::ResultAttrNum, DontDelete|ReadOnly, 0 },
    { "className", (intptr_t)JSSVGFETurbulenceElement::ClassNameAttrNum, DontDelete|ReadOnly, 0 },
    { "style", (intptr_t)JSSVGFETurbulenceElement::StyleAttrNum, DontDelete|ReadOnly, 0 },
    { "constructor", (intptr_t)JSSVGFETurbulenceElement::ConstructorAttrNum, DontEnum, 0 },
    { 0, 0, 0, 0 }
};

static const HashTable JSSVGFETurbulenceElementTable = { 255, JSSVGFETurbulenceElementTableValues, 0 };

/* Hash table for constructor */

static const HashTableValue JSSVGFETurbulenceElementConstructorTableValues[7] =
{
    { "SVG_TURBULENCE_TYPE_UNKNOWN", (intptr_t)0, DontDelete|ReadOnly, 0 },
    { "SVG_TURBULENCE_TYPE_FRACTALNOISE", (intptr_t)1, DontDelete|ReadOnly, 0 },
    { "SVG_TURBULENCE_TYPE_TURBULENCE", (intptr_t)2, DontDelete|ReadOnly, 0 },
    { "SVG_STITCHTYPE_UNKNOWN", (intptr_t)0, DontDelete|ReadOnly, 0 },
    { "SVG_STITCHTYPE_STITCH", (intptr_t)1, DontDelete|ReadOnly, 0 },
    { "SVG_STITCHTYPE_NOSTITCH", (intptr_t)2, DontDelete|ReadOnly, 0 },
    { 0, 0, 0, 0 }
};

static const HashTable JSSVGFETurbulenceElementConstructorTable = { 127, JSSVGFETurbulenceElementConstructorTableValues, 0 };

class JSSVGFETurbulenceElementConstructor : public DOMObject {
public:
    JSSVGFETurbulenceElementConstructor(ExecState* exec)
        : DOMObject(exec->lexicalGlobalObject()->objectPrototype())
    {
        putDirect(exec->propertyNames().prototype, JSSVGFETurbulenceElementPrototype::self(exec), None);
    }
    virtual bool getOwnPropertySlot(ExecState*, const Identifier&, PropertySlot&);
    JSValue* getValueProperty(ExecState*, int token) const;
    virtual const ClassInfo* classInfo() const { return &s_info; }
    static const ClassInfo s_info;

    virtual bool implementsHasInstance() const { return true; }
};

const ClassInfo JSSVGFETurbulenceElementConstructor::s_info = { "SVGFETurbulenceElementConstructor", 0, &JSSVGFETurbulenceElementConstructorTable, 0 };

bool JSSVGFETurbulenceElementConstructor::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGFETurbulenceElementConstructor, DOMObject>(exec, &JSSVGFETurbulenceElementConstructorTable, this, propertyName, slot);
}

JSValue* JSSVGFETurbulenceElementConstructor::getValueProperty(ExecState* exec, int token) const
{
    // The token is the numeric value of its associated constant
    return jsNumber(exec, token);
}

/* Hash table for prototype */

static const HashTableValue JSSVGFETurbulenceElementPrototypeTableValues[8] =
{
    { "SVG_TURBULENCE_TYPE_UNKNOWN", (intptr_t)0, DontDelete|ReadOnly, 0 },
    { "SVG_TURBULENCE_TYPE_FRACTALNOISE", (intptr_t)1, DontDelete|ReadOnly, 0 },
    { "SVG_TURBULENCE_TYPE_TURBULENCE", (intptr_t)2, DontDelete|ReadOnly, 0 },
    { "SVG_STITCHTYPE_UNKNOWN", (intptr_t)0, DontDelete|ReadOnly, 0 },
    { "SVG_STITCHTYPE_STITCH", (intptr_t)1, DontDelete|ReadOnly, 0 },
    { "SVG_STITCHTYPE_NOSTITCH", (intptr_t)2, DontDelete|ReadOnly, 0 },
    { "getPresentationAttribute", (intptr_t)jsSVGFETurbulenceElementPrototypeFunctionGetPresentationAttribute, DontDelete|Function, 1 },
    { 0, 0, 0, 0 }
};

static const HashTable JSSVGFETurbulenceElementPrototypeTable = { 127, JSSVGFETurbulenceElementPrototypeTableValues, 0 };

const ClassInfo JSSVGFETurbulenceElementPrototype::s_info = { "SVGFETurbulenceElementPrototype", 0, &JSSVGFETurbulenceElementPrototypeTable, 0 };

JSObject* JSSVGFETurbulenceElementPrototype::self(ExecState* exec)
{
    static const Identifier* prototypeIdentifier = new Identifier(exec, "[[JSSVGFETurbulenceElement.prototype]]");
    return JSC::cacheGlobalObject<JSSVGFETurbulenceElementPrototype>(exec, *prototypeIdentifier);
}

bool JSSVGFETurbulenceElementPrototype::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticPropertySlot<JSSVGFETurbulenceElementPrototype, JSObject>(exec, &JSSVGFETurbulenceElementPrototypeTable, this, propertyName, slot);
}

JSValue* JSSVGFETurbulenceElementPrototype::getValueProperty(ExecState* exec, int token) const
{
    // The token is the numeric value of its associated constant
    return jsNumber(exec, token);
}

const ClassInfo JSSVGFETurbulenceElement::s_info = { "SVGFETurbulenceElement", &JSSVGElement::s_info, &JSSVGFETurbulenceElementTable , 0 };

JSSVGFETurbulenceElement::JSSVGFETurbulenceElement(JSObject* prototype, SVGFETurbulenceElement* impl)
    : JSSVGElement(prototype, impl)
{
}

bool JSSVGFETurbulenceElement::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSVGFETurbulenceElement, Base>(exec, &JSSVGFETurbulenceElementTable, this, propertyName, slot);
}

JSValue* JSSVGFETurbulenceElement::getValueProperty(ExecState* exec, int token) const
{
    switch (token) {
    case BaseFrequencyXAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());
        RefPtr<SVGAnimatedNumber> obj = imp->baseFrequencyXAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case BaseFrequencyYAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());
        RefPtr<SVGAnimatedNumber> obj = imp->baseFrequencyYAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case NumOctavesAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());
        RefPtr<SVGAnimatedInteger> obj = imp->numOctavesAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case SeedAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());
        RefPtr<SVGAnimatedNumber> obj = imp->seedAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case StitchTilesAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());
        RefPtr<SVGAnimatedEnumeration> obj = imp->stitchTilesAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case TypeAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());
        RefPtr<SVGAnimatedEnumeration> obj = imp->typeAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case XAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());
        RefPtr<SVGAnimatedLength> obj = imp->xAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case YAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());
        RefPtr<SVGAnimatedLength> obj = imp->yAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case WidthAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());
        RefPtr<SVGAnimatedLength> obj = imp->widthAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case HeightAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());
        RefPtr<SVGAnimatedLength> obj = imp->heightAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ResultAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());
        RefPtr<SVGAnimatedString> obj = imp->resultAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case ClassNameAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());
        RefPtr<SVGAnimatedString> obj = imp->classNameAnimated();
        return toJS(exec, obj.get(), imp);
    }
    case StyleAttrNum: {
        SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(impl());
        return toJS(exec, WTF::getPtr(imp->style()));
    }
    case ConstructorAttrNum:
        return getConstructor(exec);
    }
    return 0;
}

JSValue* JSSVGFETurbulenceElement::getConstructor(ExecState* exec)
{
    static const Identifier* constructorIdentifier = new Identifier(exec, "[[SVGFETurbulenceElement.constructor]]");
    return JSC::cacheGlobalObject<JSSVGFETurbulenceElementConstructor>(exec, *constructorIdentifier);
}

JSValue* jsSVGFETurbulenceElementPrototypeFunctionGetPresentationAttribute(ExecState* exec, JSObject*, JSValue* thisValue, const ArgList& args)
{
    if (!thisValue->isObject(&JSSVGFETurbulenceElement::s_info))
        return throwError(exec, TypeError);
    JSSVGFETurbulenceElement* castedThisObj = static_cast<JSSVGFETurbulenceElement*>(thisValue);
    SVGFETurbulenceElement* imp = static_cast<SVGFETurbulenceElement*>(castedThisObj->impl());
    const UString& name = args.at(exec, 0)->toString(exec);


    JSC::JSValue* result = toJS(exec, WTF::getPtr(imp->getPresentationAttribute(name)));
    return result;
}


}

#endif // ENABLE(SVG) && ENABLE(SVG_FILTERS)
